package io.github.nheuermann.m2spreadsheet.tests.folder;

import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.runners.Parameterized.Parameters;

import io.github.nheuermann.m2spreadsheet.tests.MockModelData;

/**
 * Concrete implementation of folder-based tests for M2Spreadsheet.
 * 
 * <p>This test suite runs all test cases found in the test cases directory.
 * Each test case is a folder containing a template and expected output.</p>
 * 
 * <p><b>Test Case Structure:</b></p>
 * <pre>
 * src/test/resources/cases/
 *   simple-list/
 *     simple-list-template.xlsx    (required)
 *     simple-list-expected.xlsx    (optional)
 *     simple-list-generated.xlsx   (generated by test)
 *     simple-list-diff.xlsx        (generated if mismatch)
 *   
 *   fmea-report/
 *     fmea-report-template.xlsx
 *     fmea-report-expected.xlsx
 * </pre>
 * 
 * @author nheuermann
 */
public class FolderBasedTemplatesTest extends AbstractSpreadsheetsTestSuite {
    
    /**
     * Test cases root directory.
     */
    private static final String TEST_CASES_ROOT = "src/test/resources/cases";
    
    /**
     * Constructor.
     * 
     * @param testFolderPath the test folder path
     */
    public FolderBasedTemplatesTest(String testFolderPath) {
        super(testFolderPath);
    }
    
    /**
     * Parameterized test data - discovers all test case folders.
     * 
     * @return collection of test folder paths
     */
    @Parameters(name = "{0}")
    public static Collection<Object[]> data() {
        return retrieveTestFolders(TEST_CASES_ROOT);
    }
    
    /**
     * Provide variables for template evaluation based on test folder.
     * This implementation provides common test data for all test cases.
     * 
     * @param testFolderPath the test folder path
     * @return map of variables
     */
    @Override
    protected Map<String, Object> getVariables(String testFolderPath) {
        Map<String, Object> variables = new HashMap<>();
        
        // Provide common test data
        variables.put("projectName", "Automotive Safety System");
        variables.put("projectCode", "ASS-2026");
        variables.put("safetyStandard", "ISO 26262");
        variables.put("asil", "ASIL-D");
        
        // Simple data for basic tests
        variables.put("items", Arrays.asList("apple", "banana", "cherry"));
        variables.put("numbers", Arrays.asList(1, 2, 3, 4, 5));
        variables.put("title", "Test Report");
        variables.put("author", "Test User");
        
        // Mock model data for complex tests
        variables.put("requirements", MockModelData.getRequirements());
        variables.put("faultTreeEvents", MockModelData.getFaultTreeBaseEvents());
        variables.put("referenceDocuments", MockModelData.getReferenceDocuments());
        variables.put("fmeaEntries", MockModelData.getFmeaEntries());
        
        // Nested data for testing nested loops
        Map<String, Object> fruit = new HashMap<>();
        fruit.put("category", "Fruit");
        fruit.put("items", Arrays.asList("apple", "banana", "orange"));
        
        Map<String, Object> vegetable = new HashMap<>();
        vegetable.put("category", "Vegetable");
        vegetable.put("items", Arrays.asList("carrot", "potato", "tomato"));
        
        List<Map<String, Object>> categories = Arrays.asList(fruit, vegetable);
        variables.put("categories", categories);
        
        return variables;
    }
}
